import Header from "../components/header";
import Footer from "../components/footer";

export const metadata = {
  title: {
    template: "%s | Learning NextJs",
    default: "Home | Learning NextJs",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
